### PR TITLE
Update to compile with `image` v0.24

### PR DESCRIPTION
**Pull request by qm3ster**
(it's basically all clippy lints all the way down)

### CODE REVIEW

**Comment by eftychis** [comment]
Great job @qm3ster!

**Comment by A6GibKm** [comment]
@kennytm is there any blocker to this? Thanks!

**Comment by LeviSchuck** [comment]
It sure would be nice to have this

**Comment by qm3ster** [comment]
@LeviSchuck you can use it as follows today. This *should* allegedly replace `qrcode` used by any dependencies as well.
```toml
[dependencies]
qrcode = "0.12"

[patch.crates-io]
qrcode = { git = "https://github.com/qm3ster/qrcode-rust", rev =  "0f75a68c7ab76c5a4ce75185a9b3367bffb7d109" }
```
Don't forget to use the commit hash (`rev`) when doing things like this, so that the untrustworthy fork owner (me, in this case) doesn't rugpull you.

**Comment by nbw** [comment]
( @qm3ster I am already using your fork, thank you 🙏 and good tip on the commit hash )

**Comment by plugwash** [comment]
I'm not the maintainer, but a couple of comments on this pr.

1. The commit messages are severely lacking. "get it to compile" (with what?), "go hog wild" (WTH is this supposed to mean)
2. It would be better to keep formatting/lint changes seperate from changes related to the new version of image.
3.

**Comment by dvc94ch** [comment]
@qm3ster are you interested in maintaining the crate under a different name? seems like @kennytm has lost interest and I'd like to loose the git dependency on your PR.

**Comment by sayanarijit** [comment]
Hi! In case no one's interested, I'm willing to overtake ownership of this crate. Two of my daily use tools depend on this.

**Comment by sayanarijit** [comment]
> I'd suggest to create a new repo with a new name, update the readme, publish a new release to crates.io and then post a link here. Thanks!

That's the final option. I am reaching out to @kennytm via mail to know if it's possible to give write access or transfer the ownership to the interested maintainer(s).

**Comment by sayanarijit** [comment]
Forked and released `qrencode`.

GitHub: https://github.com/sayanarijit/qrencode
Crate: https://crates.io/crates/qrencode

Currently, this forked release contains dependency upgrades and minor cleanups. I'll do a proper cleanup later. Any help from the community is appreciated.

**Pull request closed without merging**
