### PR TITLE
Add 'width' and 'height' properties to SVG output

### PR DESCRIPTION
**Pull request by flosse**
Currently `width` and `height` are only used for the `ViewBox` property.
This commit attaches the `width` and `height` properties to the svg element.

It's not really a proper way and it's a breaking change.
I'll let you know as soon as I found a better solution.

What do you think?

### CODE REVIEW

**Comment by jkcclemens** [comment]
For what it's worth, this breaks scaling in webpages. The entire purpose of https://github.com/kennytm/qrcode-rust/pull/24 was to fix scaling. By adding these properties, CSS can no longer set the height and width of an SVG, locking it to the dimensions in the height/width attributes, which means the SVG can neither scale up nor down, defeating the point of an SVG.

**Comment by flosse** [comment]
@jkcclemens Do you have an idea how to solve it?

**Comment by jkcclemens** [comment]
Yes, remove the width and height attributes. `viewBox` is correct.

Presumably you made this PR because it solved some issue, so that solution would break your use-case. The important question becomes what issue does this PR solve, then?

**Comment by allsey87** [comment]
I agree with @anna-is-cute, this PR is a mistake and should be reverted

**Pull request merged**
